(() => {
const STREAM_URL='https://stream.zeno.fm/rgfniwauxxdtv';
const METADATA_URL='https://stream.lexxradio.com/status-json.xsl';
const DEFAULT_IMAGE='logo-lexradio.png';
const audio=new Audio(STREAM_URL); audio.preload='none'; audio.crossOrigin='anonymous';
const $=s=>document.querySelector(s); const play=$('#playBtn'), hero=$('#heroPlay'), vol=$('#volumeSlider'), title=$('#songTitle'), artist=$('#artistName'), art=$('#albumArt'), status=$('#status-text');
let playing=false,loading=false,timer=null,current='';
const escapeHTML=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setPlayUI(on){playing=on;if(play){play.textContent=on?'Ⅱ':'▶';play.setAttribute('aria-label',on?'Pausar':'Reproducir')}if(hero)hero.textContent=on?'Ⅱ PAUSAR':'▶ ESCUCHAR EN VIVO'}
async function toggle(){if(loading)return;if(playing){audio.pause();setPlayUI(false);if(timer){clearInterval(timer);timer=null}return}loading=true;if(play)play.textContent='…';try{await audio.play();setPlayUI(true);fetchMetadata();timer=setInterval(fetchMetadata,10000)}catch(e){console.error(e);setPlayUI(false);alert('No se pudo conectar con la transmisión. Intentá nuevamente.')}finally{loading=false}}
play?.addEventListener('click',toggle);hero?.addEventListener('click',toggle);vol?.addEventListener('input',()=>audio.volume=Number(vol.value));audio.volume=Number(vol?.value||.75);audio.addEventListener('error',()=>{setPlayUI(false);loading=false});
function recent(){try{return JSON.parse(localStorage.getItem('lexradio_recently_played'))||[]}catch{return[]}}
function saveRecent(label){if(!label)return;let list=recent();if(list[0]?.label===label)return;list.unshift({label,time:new Date().toLocaleTimeString('es-CR',{hour:'2-digit',minute:'2-digit'})});list=list.slice(0,30);localStorage.setItem('lexradio_recently_played',JSON.stringify(list));renderRecent(list)}
function renderRecent(list=recent()){const el=$('#recentlyPlayedList');if(!el)return;el.innerHTML=list.length?list.slice(0,8).map(x=>`<li>${escapeHTML(x.label)} <small>${escapeHTML(x.time)}</small></li>`).join(''):'<li>El historial aparecerá al escuchar.</li>'}
async function fetchMetadata(){try{const r=await fetch(`${METADATA_URL}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('metadata');const d=await r.json();let src=d?.icestats?.source;if(Array.isArray(src))src=src.find(x=>x.title)||src[0];const full=src?.title?.trim();if(!full||full===current)return;if(current)saveRecent(current);current=full;let a='',s=full;if(full.includes(' - ')){const p=full.split(' - ');a=p.shift().trim();s=p.join(' - ').trim()}title.textContent=s;artist.textContent=a||'LEX Radio';fetchArtwork(a,s)}catch(e){console.warn('Metadata temporalmente no disponible',e)}}
async function fetchArtwork(a,s){if(!a||!s){art.src=DEFAULT_IMAGE;return}try{const r=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(a+' '+s)}&entity=song&limit=1`);const d=await r.json();const u=d.results?.[0]?.artworkUrl100;art.src=u?u.replace('100x100','600x600'):DEFAULT_IMAGE}catch{art.src=DEFAULT_IMAGE}}
renderRecent();fetchMetadata();
const form=$('#requestForm');form?.addEventListener('submit',e=>{e.preventDefault();const n=$('#reqName').value.trim(),s=$('#reqSong').value.trim(),a=$('#reqArtist').value.trim(),m=$('#reqMessage').value.trim();const text=`🎶 Petición para LEX Radio\nNombre: ${n}\nCanción: ${s}\nArtista: ${a}${m?`\nDedicatoria: ${m}`:''}`;window.open(`https://wa.me/50684794991?text=${encodeURIComponent(text)}`,'_blank','noopener')});
let deferredPrompt=null;const install=$('#installButton');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;install?.classList.add('ready')});install?.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else if(/iphone|ipad|ipod/i.test(navigator.userAgent)){alert('En iPhone: tocá Compartir y luego “Agregar a pantalla de inicio”.')}else alert('Usá la opción “Instalar aplicación” o “Agregar a pantalla de inicio” de tu navegador.')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.error));
window.OneSignalDeferred=window.OneSignalDeferred||[];window.OneSignalDeferred.push(async OneSignal=>{try{await OneSignal.init({appId:'fe22a797-a48d-4d38-83a1-0c4d34e88a38',autoResubscribe:true,notifyButton:{enable:false}})}catch(e){console.warn(e)}});
})();